export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          nome: string;
          email: string;
          perfil: "Administrador" | "Gestor" | "Consultor" | "Trainee" | "Secretaria" | "Indicador";
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          nome?: string;
          email?: string;
          perfil?: "Administrador" | "Gestor" | "Consultor" | "Trainee" | "Secretaria" | "Indicador";
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          nome?: string;
          email?: string;
          perfil?: "Administrador" | "Gestor" | "Consultor" | "Trainee" | "Secretaria" | "Indicador";
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      leads: {
        Row: {
          id: string;
          nome: string;
          telefone: string;
          cidade: string;
          status: string;
          observacoes: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          nome?: string;
          telefone?: string;
          cidade?: string;
          status?: string;
          observacoes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          nome?: string;
          telefone?: string;
          cidade?: string;
          status?: string;
          observacoes?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      indicadores: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          nome: string;
          telefone: string;
          whatsapp: string;
          email: string;
          cidade: string;
          estado: string;
          cpf: string;
          pix: string;
          origem: string;
          profissao: string;
          data_entrada: string | null;
          status: string;
          observacoes: string;
          ativo: boolean;
          usuario_id: string;
          pipeline_stage: string;
          grupo_whatsapp: boolean;
          link_grupo: string;
          grupo_criado: boolean;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          nome?: string;
          telefone?: string;
          whatsapp?: string;
          email?: string;
          cidade?: string;
          estado?: string;
          cpf?: string;
          pix?: string;
          origem?: string;
          profissao?: string;
          data_entrada?: string;
          status?: string;
          observacoes?: string;
          ativo?: boolean;
          usuario_id?: string;
          pipeline_stage?: string;
          grupo_whatsapp?: boolean;
          link_grupo?: string;
          grupo_criado?: boolean;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          nome?: string;
          telefone?: string;
          whatsapp?: string;
          email?: string;
          cidade?: string;
          estado?: string;
          cpf?: string;
          pix?: string;
          origem?: string;
          profissao?: string;
          data_entrada?: string;
          status?: string;
          observacoes?: string;
          ativo?: boolean;
          usuario_id?: string;
          pipeline_stage?: string;
          grupo_whatsapp?: boolean;
          link_grupo?: string;
          grupo_criado?: boolean;
        };
      };
      contatos_indicados: {
        Row: {
          id: string;
          indicador_id: string;
          nome: string;
          telefone: string;
          cidade: string;
          status: string;
          observacoes: string;
          created_at: string;
          updated_at: string;
          usuario_id: string;
        };
        Insert: {
          id?: string;
          indicador_id: string;
          nome?: string;
          telefone?: string;
          cidade?: string;
          status?: string;
          observacoes?: string;
          created_at?: string;
          updated_at?: string;
          usuario_id: string;
        };
        Update: {
          id?: string;
          indicador_id?: string;
          nome?: string;
          telefone?: string;
          cidade?: string;
          status?: string;
          observacoes?: string;
          created_at?: string;
          updated_at?: string;
          usuario_id?: string;
        };
      };
      comissoes_indicadores: {
        Row: {
          id: string;
          indicador_id: string;
          valor: number;
          status: string;
          pix: string;
          data_pagamento: string | null;
          observacoes: string;
          usuario_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          indicador_id: string;
          valor?: number;
          status?: string;
          pix?: string;
          data_pagamento?: string | null;
          observacoes?: string;
          usuario_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          indicador_id?: string;
          valor?: number;
          status?: string;
          pix?: string;
          data_pagamento?: string | null;
          observacoes?: string;
          usuario_id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      parceiros: {
        Row: {
          id: string;
          nome: string;
          empresa: string;
          segmento: string;
          telefone: string;
          email: string;
          cidade: string;
          status: string;
          nivel_parceria: string;
          comissao_percentual: number;
          ultimo_contato: string | null;
          observacoes: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          nome?: string;
          empresa?: string;
          segmento?: string;
          telefone?: string;
          email?: string;
          cidade?: string;
          status?: string;
          nivel_parceria?: string;
          comissao_percentual?: number;
          ultimo_contato?: string | null;
          observacoes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          nome?: string;
          empresa?: string;
          segmento?: string;
          telefone?: string;
          email?: string;
          cidade?: string;
          status?: string;
          nivel_parceria?: string;
          comissao_percentual?: number;
          ultimo_contato?: string | null;
          observacoes?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      recrutamento: {
        Row: {
          id: string;
          nome: string;
          telefone: string;
          email: string;
          cidade: string;
          vaga_interesse: string;
          etapa: string;
          fonte: string;
          score_aderencia: number;
          disponibilidade_inicio: string | null;
          status: string;
          observacoes: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          nome?: string;
          telefone?: string;
          email?: string;
          cidade?: string;
          vaga_interesse?: string;
          etapa?: string;
          fonte?: string;
          score_aderencia?: number;
          disponibilidade_inicio?: string | null;
          status?: string;
          observacoes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          nome?: string;
          telefone?: string;
          email?: string;
          cidade?: string;
          vaga_interesse?: string;
          etapa?: string;
          fonte?: string;
          score_aderencia?: number;
          disponibilidade_inicio?: string | null;
          status?: string;
          observacoes?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      agendas: {
        Row: {
          id: string;
          usuario_id: string;
          indicador_id: string | null;
          cliente_id: string | null;
          titulo: string;
          descricao: string;
          data_hora: string;
          duracao_minutos: number;
          tipo: string;
          status: string;
          local_online: string;
          notas_conclusao: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          usuario_id: string;
          indicador_id?: string | null;
          cliente_id?: string | null;
          titulo?: string;
          descricao?: string;
          data_hora: string;
          duracao_minutos?: number;
          tipo?: string;
          status?: string;
          local_online?: string;
          notas_conclusao?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          usuario_id?: string;
          indicador_id?: string | null;
          cliente_id?: string | null;
          titulo?: string;
          descricao?: string;
          data_hora?: string;
          duracao_minutos?: number;
          tipo?: string;
          status?: string;
          local_online?: string;
          notas_conclusao?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      pos_venda: {
        Row: {
          id: string;
          usuario_id: string;
          cliente_id: string;
          agenda_id: string | null;
          status: string;
          priority: string;
          satisfaction: number;
          next_contact_at: string | null;
          last_contact_at: string | null;
          channel: string;
          needs_attention: boolean;
          observacoes: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          usuario_id: string;
          cliente_id: string;
          agenda_id?: string | null;
          status?: string;
          priority?: string;
          satisfaction?: number;
          next_contact_at?: string | null;
          last_contact_at?: string | null;
          channel?: string;
          needs_attention?: boolean;
          observacoes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          usuario_id?: string;
          cliente_id?: string;
          agenda_id?: string | null;
          status?: string;
          priority?: string;
          satisfaction?: number;
          next_contact_at?: string | null;
          last_contact_at?: string | null;
          channel?: string;
          needs_attention?: boolean;
          observacoes?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      user_settings: {
        Row: {
          id: string;
          usuario_id: string;
          calendar_integration_enabled: boolean;
          calendar_email: string;
          whatsapp_integration_enabled: boolean;
          whatsapp_webhook_url: string;
          whatsapp_api_key: string;
          notification_email: boolean;
          notification_whatsapp: boolean;
          language: string;
          page_size: number;
          default_indicator_status: string;
          compact_sidebar: boolean;
          auto_refresh_dashboard: boolean;
          dashboard_refresh_seconds: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          usuario_id: string;
          calendar_integration_enabled?: boolean;
          calendar_email?: string;
          whatsapp_integration_enabled?: boolean;
          whatsapp_webhook_url?: string;
          whatsapp_api_key?: string;
          notification_email?: boolean;
          notification_whatsapp?: boolean;
          language?: string;
          page_size?: number;
          default_indicator_status?: string;
          compact_sidebar?: boolean;
          auto_refresh_dashboard?: boolean;
          dashboard_refresh_seconds?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          usuario_id?: string;
          calendar_integration_enabled?: boolean;
          calendar_email?: string;
          whatsapp_integration_enabled?: boolean;
          whatsapp_webhook_url?: string;
          whatsapp_api_key?: string;
          notification_email?: boolean;
          notification_whatsapp?: boolean;
          language?: string;
          page_size?: number;
          default_indicator_status?: string;
          compact_sidebar?: boolean;
          auto_refresh_dashboard?: boolean;
          dashboard_refresh_seconds?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
