BEGIN;

ALTER TABLE indicadores
  ADD COLUMN IF NOT EXISTS whatsapp TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS cidade TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS estado TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS cpf TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS pix TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS origem TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS profissao TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS data_entrada DATE,
  ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'Novo',
  ADD COLUMN IF NOT EXISTS observacoes TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS ativo BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS usuario_id UUID REFERENCES auth.users(id) ON DELETE CASCADE;

COMMIT;
