BEGIN;

ALTER TABLE public.indicadores
  ADD COLUMN IF NOT EXISTS whatsapp TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS profissao TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS data_entrada TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS pipeline_stage TEXT NOT NULL DEFAULT 'Novo Indicador';

COMMIT;
